homepage_route: "home"
routes:
    home: "Main:home"
    login: "Main:login"
    logout: "Main:logout"
    register: "Main:register"
    tweet: "Main:tweet"
    addTweet: "Main:addTweet"
    profileUser : "Main:profile"
